version: '3.7'

services:
  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: "YOUR_USER"
      MINIO_SECRET_KEY: "YOUR_PASSWORD"
    command: server /data --console-address ":9001"

volumes:
  minio-data:
    driver: local
